name: Notifications

on: [push]

jobs:
  stale:
    name: Discord Commits
    runs-on: ubuntu-latest
    steps:
    - name: Discord Commits
      uses: dearimgui/github_discord_notifier@latest
      with:
        discord-webhook: ${{ secrets.DISCORD_WEBHOOK_COMMITS }}
        github-token: ${{ github.token }}
        action-task: discord-commits
        discord-filter: "'{{ github.branch }}' == 'master'"
        discord-username: GitHub
